### ISSUE TITLE
module not found / typings outdated

### ISSUE THREAD

**Issue by rendall** [ivogabe/gulp-typescript#462]
tsc compiles fine.  I verified through --traceResolution that it finds the type definitions for all referenced modules in node_modules.

However, with gulp-typescript I got several modules not found errors, including module "d3" not found error.  

So I followed the advice to add **typings** to the gulp.src options for the compile task.  Since the IDE would throw errors for duplicate declarations, I added `"typeRoots": [ "./node_modules/@types" ]` to the tsconfig.json compiler options, which has the effect of *excluding* `./typings` from the compiler.  Handily, gulp-typescript does not use that compilerOption, so it seemed like a neat solution.  IDE and tsc uses one set of type declarations (node_modules/@types) and gulp-typescript uses **typings**.

However, all modules except d3 have up to date (or well enough) type definitions.  D3 typings throws such errors as:

`error TS2339: Property 'scaleTime' does not exist on type 'typeof d3'.
`
To fix this, I tried adding the filepath "node_modules/@types/d3/index.d.ts" to gulp.src for the task like so: 
`gulp.src(["src/**/*.ts", "typings/**/*.d.ts", "node_modules/@types/d3/index.d.ts"])`

But I get errors:

```
node_modules\@types\d3\index.d.ts(6,1): error TS1128: Declaration or statement expected.
node_modules\@types\d3\index.d.ts(6,11): error TS1005: ';' expected.
node_modules\@types\d3\index.d.ts(6,23): error TS1005: '{' expecte
```

**Expected behavior:**

gulp-typescript finds the d3 module or otherwise behaves exactly like tsc does.

**Actual behavior:**

gulp-typescript does not find d3 in node_modules and throws an error because of that.

**gulpfile:**

```javascript
const tsc = require("gulp-typescript");
const tsProject = tsc.createProject("tsconfig.json");
const tslint = require('gulp-tslint');

const gulpCompileSrcs = ["src/**/*.ts", "typings/**/*.d.ts", "node_modules/@types/d3/index.d.ts"];

gulp.task('tslint', () => {
    return gulp.src("src/**/*.ts")
        .pipe(tslint({
            formatter: 'prose'
        }))
        .pipe(tslint.report());
});



gulp.task("compile", ["tslint"], () => {
    let tsResult = gulp.src(gulpCompileSrcs)
        .pipe(sourcemaps.init())
        .pipe(tsc(tsProject));
    return tsResult.js
        .pipe(sourcemaps.write(".", { sourceRoot: '/src' }))
        .pipe(gulp.dest("wwwroot"));
});
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "outDir": "wwwroot/app",
    "target": "es5",
    "lib": [ "dom", "es6" ],
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": false,
    "typeRoots": [ "./node_modules/@types" ]
  },
  "exclude": [
    "gulpfile.ts",
    "node_modules",
    "typings"
  ]
}
```

**Comment by ivogabe** [comment]
Could you replace `gulp.src("src/**/*.ts")` with `tsProject.src()`? Then you should pass the same files to the compiler as `tsc` does. And are you using the latest versions of gulp-typescript and TypeScript?

**Comment by dunecatnat** [comment]
@ivogabe I upgraded the versions of typescript@2.0.8, can't risk upgrading to the most recent version yet, and gulp-typescript@3.1.3, which solved the errors mentioned above. Now we are having a different error: 
`[gulp-typescript] 1316 Global module exports may only appear at top level.
> file: ..../typings/modules/d3/index.d.ts:
> [13] export as namespace d3;`
I am wondering if the problem d3 typings or gulp-typescript or something else.
We use angular@1.5.8 and c3@0.14.10 and d3@3.5.2 and d3 typings v3.5

**Comment by egorovsa** [comment]
Absolutely same problem... tsc compiles fine.
```
$ gulp -v
 CLI version 3.9.1
 Local version 3.9.1

$ tsc -v
Version 2.1.4

$ node -v
v6.4.0

 "gulp-typescript": "2.13.0",
```

When i try like:

**Gulp task:**
```
    var tsResult = gulp.src([
            './src/ts/**/*.ts',
            './src/ts/**/*.tsx',
            '!./node_modules',
            './node_modules/@types/**/*.d.ts'
        ])
        .pipe(ts({
            noImplicitAny: false,
            noEmitOnError: true,
            declarationFiles: false,
            noExternalResolve: false,
            removeComments: false,
            diagnostics: true,
            sourceMap: true,
            module: "commonjs",
            target: "es5",
            jsx: "react"
        }));

    return tsResult.js
        .pipe(gulp.dest('./dist/'));
```

then i have :
```
node_modules/@types/node/index.d.ts(284,40): error TS1110: Type expected.
node_modules/@types/npm/index.d.ts(6,1): error TS1084: Invalid 'reference' directive syntax.
node_modules/@types/react-dom/index.d.ts(6,1): error TS1128: Declaration or statement expected.
node_modules/@types/react-dom/index.d.ts(6,11): error TS1005: ';' expected.
node_modules/@types/react-dom/index.d.ts(6,29): error TS1005: '{' expecte
```
==================
When i try second method:

**Gulp task:**
```
function typeScriptCompile() {
    var tsProject = ts.createProject('./tsconfig.json');

    var tsResult = tsProject.src([
            './src/ts/**/*.ts',
            './src/ts/**/*.tsx',
        ])
        .pipe(ts(tsProject));

    return tsResult.js
        .pipe(gulp.dest('./dist/'));
}
```
**tsconfig.json**

```
{
  "compilerOptions": {
    "module": "commonjs",
    "jsx": "react",
    "target": "es5",
    "lib": [ "dom", "es6" ],
    "outDir": "dist",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": false,
    "typeRoots": [
      "./node_modules/@types/"
    ]
  },
  "exclude": [
    "node_modules"
  ]
}
```

i have result 
```
src/ts/client.ts(3,24): error TS2307: Cannot find module 'react'.
src/ts/client.ts(4,27): error TS2307: Cannot find module 'react-dom'.
src/ts/client.ts(5,38): error TS2307: Cannot find module 'react-router'.
src/ts/components/app.tsx(1,24): error TS2307: Cannot find module 'react'.
src/ts/components/app.tsx(20,23): error TS2339: Property 'props' does not exist on type 'AppComponent'.
src/ts/components/pages/main-page.tsx(1,24): error TS2307: Cannot find module 'react'.
```

**Comment by ivogabe** [comment]
@dunecatnat D3 typings might only work with TS2.1, so you might need to update further. Though I must say that I'm not familiar with the typings for D3. Anyway I do think that `tsc` would give the same error.
