### ISSUE TITLE
2.13.1 logs errors for previously functional declarations behavior

### ISSUE THREAD

**Issue by brphelps** [ivogabe/gulp-typescript#337]
**Expected behavior:**

When I use gulp-typescript, setting the declaration parameter in options to a truthy value is evaluated in a truthy manner.

**Actual behavior:**

I see a console error after upgrading to 2.13.1 describing my truth declaration value (undefined) as being inappropriately defined.

error TS5024: Compiler option 'declaration' requires a value of type boolean.

**Your gulpfile:**

```javascript

_tsProject = plugins.typescript.createProject(tsConfigPath, {
            typescript: require('typescript'),
            declaration: context.generateTypings && true
        });

```

**Comment by ivogabe** [comment]
The declaration option expects a boolean, so the message is correct. In previous versions this error wasn't shown due to bug #247, which has been fixed in the latest release.

**Comment by brphelps** [comment]
I guess I'll say that this seems like a surprising change to get in a minor version change, since it breaks things which previously were working fine (not to mention that it's still a truthy value :) ). I would've expected the introduction of warnings and then maybe eventually a hard break.

**Comment by ivogabe** [comment]
> I would've expected the introduction of warnings and then maybe eventually a hard break.

The error does not block the rest of the build proces, and don't change the exit code. So it isn't a hard break. The message does contain the word 'error', because TypeScript calls all warnings errors.

**Comment by brphelps** [comment]
This may be unrelated to the log message, but the set of changes that came in ended up preventing my existing task (which is using gulp-typescript) from completing. I rolled back to version 2.13.0 statically to unblock my team members. I'll dig further to see why the task no longer completes with the 2.13.1 changes.

**Comment by lotz** [comment]
Just throwing a "me too" on here with @brphelps's comment. We are seeing the same issue, so it is not isolated to just him.

**Comment by ivogabe** [comment]
@lotz Does it only show a message or does it also break the build somehow? Such as a different exit code or blocking a next step of the build.

**Comment by ivogabe** [comment]
@brphelps Did you set the `rootDir` option? The new version did introduce a regression with that option.

**Comment by brphelps** [comment]
I did, sorry about the delay in getting back to you. That regression is likely leading to the behavior that I was mistaking the logged error to have caused.
